### ISSUE TITLE
p2p topology status: research and follow up on how to add more data

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#1355]
## Is your feature request related to a problem/context ? Please describe if applicable.

Having a way to give more information about the overall known peers of a node could help with tracking and debugging the p2p protocol and for the stake pool owners to visualise how connected is one node.

## Describe the solution you'd like

- [ ] can we attach the node version in the gossip of a node ? This way it would become available to the network and we would know how old a node is.
    - This information will need to lie in the `NodeProfile` info, currently `poldercast` crate does not allow random metadata to be included in the gossips. So we will need to see how to include this without breaking `poldercast` APIs;
    - [ ] bonus is that we can update the network to know what kind of protocol feature one node supports
    - [ ] we can also adapt the `policy` to prevent connecting to nodes that are not compatible anymore;
- [ ] log in the `Node`'s logs the latest block announcement
    - this does not really mean it is the last block of the node for the current branch. It is not necessarily the `tip` of the blockchain. however logging this can give some information about a block propagation event and how it has been propagated to the network;
    - [ ] `poldercast` has some logging mechanism available, we might just need to extend it to allow for more generic data
- [ ] expose our network settings (topics, policy and node id) in `network/p2p/settings`;
- [ ] allow resetting our topics preferences
    - this will need few changes in `poldercast`
- [ ] allow resetting our node_id
    - this will need few changes in `poldercast`
- [ ] policy management: allow blacklisting of entries via config file or via REST APIs
- [ ] update the policy to have a more incremental approach to quarantine (and even to quarantine longer if issues keep repeating).

## Additional context

Not all of these should be implemented, but some are feasible with some changes in the `poldercast` crate.
