### ISSUE TITLE
Service management

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#1770]
In the research done in #1597 we have worked on implementing the base code environment for managing and monitoring different services. This has been made possible utilising the new stabilised `async/await` APIs from the Rust Programming language. Now this Epic will describe the work to do for the integration with in Jörmungandr and propose future improvements and updates on some part of the service management.

## Monitoring and controlling the watchdog and services

**basic features done in #1597**:

- [x] starting a service dynamically. Being able to restart a service dynamically was necessary in order to be able reboot a lagging service, update the settings of a service or just start a service only if needed.
- [x] stopping a service dynamically. Being able to stop a service dynamically allows to stop a service when it is no longer needed or if the service is lagging and need restarted
- [x] automatically re-connectable intercommunication tools. Established connections with a service need to be able to restart automatically if appropriate.
- [x] collecting stats on a running service, up time, number of restarts etc.
- [x] adding command line and config file settings format.

### Update on the settings management

- [ ] need a way to have a compatibility layer with previous format (for CLI and for config file format):
- [ ] allow updating the settings dynamically from the `WatchdogQuery` (request update of the settings of a given service) and propagate the update to the appropriate service. There is already a settings updater and reader available who will propagate update events appropriately. Missing the links from the `WatchdogQuery` to the `Watchdog` and to update the setting;
- [ ] on update, it would make sense to store the settings changes in the configuration file too so rebooting the node will keep the settings changes

### Update on the state management:

- [ ] missing method for storing/reloading a state to/from a persistent storage format;
- [ ] add the missing handler to store the state on update. There is already the Reader, updater available with #1597 but this need to be now connected 

## Integration in Jörmungandr

- [ ] need a way to have a compatibility layer with previous format (for CLI and for config file format) (_same issue as in the [Update on the settings management] part_)

Integration can be done by allowing the 2 worlds to live together at the beginning, with dynamically choosing to switch to the new experimental approach of managing the services. This will allow a smoother transition and also to test further the implementation of the watchdog and intercom.

- [ ] split the start up process to allow the old task to start and other backend watchdog to start;
- [ ] identify the different inter communication bits of the different services and implement a compatibility layer for the common part between old and new way of managing the services.
