### ISSUE TITLE
Add support for Genesis consensus

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/jormungandr#19]
* [x] VRF implementation
* [x] KES implementation
* [x] Block leadership selection
* [x] Get distribution stakes
* [x] Chain selection in `k`
* [x] Chain selection out of `k`
