### ISSUE TITLE
Rest API v1

### ISSUE THREAD

**Issue by rinor** [input-output-hk/jormungandr#2056]
# Rest API v1

This ticket tracks the design of a new **OpenAPI** *Specification* for Jörmungandr node,
referred as **Jörmungandr Rest API v1**.

This will be an additional specification to the existing **Jörmungandr Rest API v0**.

The aim is to improve and enhance the existing one accomodating the new upcomming features/needs and to build upon the experience/feedback acummulated during the past months from the users operating the node on the ITN.

---

## Implementation Flow

The process has to be simple and flexible so it can be easily adapted to be valuable/efficient for all community and team members. The following provides a general flow that can be followed during the whole process.

![api_v1_flow](https://user-images.githubusercontent.com/1160245/78912333-fdbd6980-7a76-11ea-82cb-3c2ea8bad267.png)

---

### technical aspect and tools

- [ ] OpenAPI Specification Version 3.0.x
- [ ] API Description Linter with GitHub Actions -
- [ ] HTTP mock server that can mimic API’s behavior -

---

## API tracking

The following table lists the _actual v0 api endpoints._ It will be used to keep track the endpoints between versions. In case we need to implement the same endpoint also on the new v1 api (probably won't) with updated/enhanced functionality, we will provide some more information also in the `Notes` field.

<details open>
  <summary>API v0 (actual status)</summary>

[API v0 definition online](https://editor.swagger.io/?url=https://raw.githubusercontent.com/input-output-hk/jormungandr/master/doc/openapi.yaml)

| Method | Endpoint                            |      /api/v0/      | /api/v1/ | Notes |
| :----: | ----------------------------------- | :----------------: | :------: | ----- |
|  GET   | account​/{account_id}               | :heavy_check_mark: |   :x:    |       |
|  GET   | block​/{block_id}                   | :heavy_check_mark: |   :x:    |       |
|  GET   | block​/{block_id}​/next_id          | :heavy_check_mark: |   :x:    |       |
|  GET   | diagnostic                          | :heavy_check_mark: |   :x:    |       |
|  GET   | fragment​/logs                      | :heavy_check_mark: |   :x:    |       |
|  GET   | leaders                             | :heavy_check_mark: |   :x:    |       |
|  POST  | leaders                             | :heavy_check_mark: |   :x:    |       |
| GET ​  | leaders​/logs                       | :heavy_check_mark: |   :x:    |       |
| DELETE | leaders​/{leader_id}                | :heavy_check_mark: |   :x:    |       |
|  POST  | message                             | :heavy_check_mark: |   :x:    |       |
|  GET   | network​/stats                      | :heavy_check_mark: |   :x:    |       |
|  GET   | network​/p2p​/non_public            | :heavy_check_mark: |   :x:    |       |
|  GET   | network​/p2p​/available             | :heavy_check_mark: |   :x:    |       |
|  GET   | network​/p2p​/quarantined           | :heavy_check_mark: |   :x:    |       |
|  GET   | network​/p2p​/view                  | :heavy_check_mark: |   :x:    |       |
|  GET   | network​/p2p​/view​/{topic}         | :heavy_check_mark: |   :x:    |       |
|  GET   | node​/stats                         | :heavy_check_mark: |   :x:    |       |
|  GET   | rewards​/epoch​/{epoch}             | :heavy_check_mark: |   :x:    |       |
|  GET   | rewards​/history​/{length}          | :heavy_check_mark: |   :x:    |       |
|  GET   | settings                            | :heavy_check_mark: |   :x:    |       |
|  GET   | shutdown                            | :heavy_check_mark: |   :x:    |       |
|  GET   | stake                               | :heavy_check_mark: |   :x:    |       |
|  GET   | stake​/{epoch}                      | :heavy_check_mark: |   :x:    |       |
|  GET   | stake_pools                         | :heavy_check_mark: |   :x:    |       |
|  GET   | stake_pool​/{pool_id}               | :heavy_check_mark: |   :x:    |       |
|  GET   | tip                                 | :heavy_check_mark: |   :x:    |       |
|  GET   | utxo​/{fragment_id}​/{output_index} | :heavy_check_mark: |   :x:    |       |
</details>

---

## v1 status

<details open>
  <summary>API v1 </summary>

[API v1 definition online]()

| Method | Endpoint | Status | Notes |
| :----: | -------- | :----: | ----- |
|        |          |        |       |
|        |          |        |       |
|        |          |        |       |
</details>
