### ISSUE TITLE
Port to tokio 1.0

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#2621]
Need to keep up with the async stack.

## Dependencies needing upgrade

- [x] tonic https://github.com/hyperium/tonic/pull/530 
- [x] ~warp https://github.com/seanmonstar/warp/issues/725~ left on 0.2 because of juniper
- [x] juniper, ~replace with asyng-graphql https://github.com/input-output-hk/jormungandr/issues/2945~ left for the time being with a tokio-compat-02 shim

**Comment by danielSanchezQ** [comment]
We have two drafts with the build complete. Sadly we will not be able to update until some of our async stacks are updated too.

At least:
- [ ] Tonic
- [ ] Warp

**Comment by mzabaluev** [comment]
Sometimes procrastination saves you some work: we should target tokio 1.0 now.
As @danielSanchezQ mentioned, this makes sense to do when tonic and warp are updated to tokio 1.0.

**Comment by danielSanchezQ** [comment]
Hyper was just updated yesterday too. So lets hope warp and tonic will do so soon too.

**Comment by eugene-babichenko** [comment]
Tonic is already on tokio 1.0, the relevant pull request in warp already has 70 comments and this is going to become a long story :D

**Comment by mzabaluev** [comment]
Reopening to incorporate #2958.
