### ISSUE TITLE
Update to parity-multiaddr

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#2699]
The audit is [failing](https://app.circleci.com/pipelines/github/input-output-hk/jormungandr/8203/workflows/2689ae89-6422-4484-ab52-1bc824929781/jobs/37095) because of a dependency on `multiaddr`, which is outdated and depends on an old `multihash` version.

Switch to `parity-multiaddr` and update the `cid` dependency in poldercast if needed.

## Work items

- [x] Update poldercast: https://github.com/primetype/poldercast/pull/29 https://github.com/primetype/poldercast/pull/30
- [x] ~Cause new poldercast release to be made~
- [x] Update jormungandr to a poldercast branch with the changes: #2710
