### ISSUE TITLE
Jormungandr Test Suite Improvements

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#746]
**Is your feature request related to a problem/context ? Please describe if applicable.**
Using Jormungandr scenario tests project is a great relief when testing multi node communication, however there is a room for small features that can help debugging problems

**Describe the solution you'd like**
- [x] Add synchronous bootstrap (in situation where we want to be sure that entire network is up)
- [x] Add option to start node in persistent mode (with storage option) for cases where we want to test blocks synchronization
- [x] Allow to use random generator from context to satisfy scenario in which we would like to send transaction to random node or shutdown random node
- [x] Option to create separate log (with trace level) for each node
- [x] Showing block tips of node on monitor part of log
- [x] Option to log to file instead to console.
- [ ] Dump all blockchain state to files (Nice to have)
- [x] Log public keys of accounts on startup
- [x] It's problematic to test earlier versions, since project uses lib instead of jcli. There is an option to select jcli and jormungandr option but it only introduce error when those are not compatible with current version

**Comment by NicolasDP** [comment]
regarding:

` Log public keys of accounts on startup`. The private keys are stored already. If you have the private keys, you have the public keys too.

`cat test_dir/scenario_title/account_name | jcli key to-public`
